joint_limits:
  group_1/joint_5:
    has_acceleration_limits: true
    max_acceleration: 5.0
  group_1/joint_7:
    has_acceleration_limits: true
    max_acceleration: 5.0
  group_1/joint_2:
    has_acceleration_limits: true
    max_acceleration: 5.0
  group_1/joint_4:
    has_acceleration_limits: true
    max_acceleration: 5.0
  group_1/joint_3:
    has_acceleration_limits: true
    max_acceleration: 5.0
  group_1/joint_1:
    has_acceleration_limits: true
    max_acceleration: 5.0
  group_1/joint_6:
    has_acceleration_limits: true
    max_acceleration: 5.0