controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz
  
    joint_1tate_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: forward_command_controller/ForwardCommandController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_5
      - joint_7
      - joint_2    
      - joint_4
      - joint_1
      - joint_6
      - joint_3
    interface_name: position

