controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz
  
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: forward_command_controller/ForwardCommandController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_b
      - joint_e
      - joint_l    
      - joint_r
      - joint_s
      - joint_t
      - joint_u
    interface_name: position

