controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz
  
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

forward_position_controller:
  ros__parameters:
    joints:
      - group_1/joint_5
      - group_1/joint_7
      - group_1/joint_2    
      - group_1/joint_4
      - group_1/joint_1
      - group_1/joint_6
      - group_1/joint_3
    interface_name: position

